// Packages
import React, { useEffect, useState, useContext } from 'react';
import { useLocation, useNavigate, Outlet } from "react-router-dom";
import { FaGithub, FaTwitter } from "react-icons/fa";

// Components
import Page from 'components/page';
import Link from 'components/link';

// Auth
import { AuthProvider, useAuth } from 'auth/auth';

export default function Plants({ ...props }) {
    return (
        <>
            <Page title={"Plants"} type={null}>
                <div className="page-padding">
                    <p> <b> TOP </b> </p>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce volutpat justo vel euismod tempus. Curabitur urna tortor, commodo ut finibus id, aliquam non tortor. Pellentesque maximus, nulla eu feugiat sagittis, diam ex viverra sapien, in faucibus lacus risus vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed iaculis pretium nulla, eu auctor felis. Vestibulum sit amet massa et arcu rhoncus porta nec id enim. Maecenas iaculis est eget nibh pharetra aliquam. Duis eleifend ligula at nulla pretium rutrum. Praesent dignissim, sapien non euismod aliquam, nunc nisl faucibus odio, quis posuere mi est eget ante. Proin varius rutrum egestas. In condimentum est ut sodales ultrices. </p>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce volutpat justo vel euismod tempus. Curabitur urna tortor, commodo ut finibus id, aliquam non tortor. Pellentesque maximus, nulla eu feugiat sagittis, diam ex viverra sapien, in faucibus lacus risus vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed iaculis pretium nulla, eu auctor felis. Vestibulum sit amet massa et arcu rhoncus porta nec id enim. Maecenas iaculis est eget nibh pharetra aliquam. Duis eleifend ligula at nulla pretium rutrum. Praesent dignissim, sapien non euismod aliquam, nunc nisl faucibus odio, quis posuere mi est eget ante. Proin varius rutrum egestas. In condimentum est ut sodales ultrices. </p>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce volutpat justo vel euismod tempus. Curabitur urna tortor, commodo ut finibus id, aliquam non tortor. Pellentesque maximus, nulla eu feugiat sagittis, diam ex viverra sapien, in faucibus lacus risus vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed iaculis pretium nulla, eu auctor felis. Vestibulum sit amet massa et arcu rhoncus porta nec id enim. Maecenas iaculis est eget nibh pharetra aliquam. Duis eleifend ligula at nulla pretium rutrum. Praesent dignissim, sapien non euismod aliquam, nunc nisl faucibus odio, quis posuere mi est eget ante. Proin varius rutrum egestas. In condimentum est ut sodales ultrices. </p>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce volutpat justo vel euismod tempus. Curabitur urna tortor, commodo ut finibus id, aliquam non tortor. Pellentesque maximus, nulla eu feugiat sagittis, diam ex viverra sapien, in faucibus lacus risus vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed iaculis pretium nulla, eu auctor felis. Vestibulum sit amet massa et arcu rhoncus porta nec id enim. Maecenas iaculis est eget nibh pharetra aliquam. Duis eleifend ligula at nulla pretium rutrum. Praesent dignissim, sapien non euismod aliquam, nunc nisl faucibus odio, quis posuere mi est eget ante. Proin varius rutrum egestas. In condimentum est ut sodales ultrices. </p>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce volutpat justo vel euismod tempus. Curabitur urna tortor, commodo ut finibus id, aliquam non tortor. Pellentesque maximus, nulla eu feugiat sagittis, diam ex viverra sapien, in faucibus lacus risus vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed iaculis pretium nulla, eu auctor felis. Vestibulum sit amet massa et arcu rhoncus porta nec id enim. Maecenas iaculis est eget nibh pharetra aliquam. Duis eleifend ligula at nulla pretium rutrum. Praesent dignissim, sapien non euismod aliquam, nunc nisl faucibus odio, quis posuere mi est eget ante. Proin varius rutrum egestas. In condimentum est ut sodales ultrices. </p>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce volutpat justo vel euismod tempus. Curabitur urna tortor, commodo ut finibus id, aliquam non tortor. Pellentesque maximus, nulla eu feugiat sagittis, diam ex viverra sapien, in faucibus lacus risus vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed iaculis pretium nulla, eu auctor felis. Vestibulum sit amet massa et arcu rhoncus porta nec id enim. Maecenas iaculis est eget nibh pharetra aliquam. Duis eleifend ligula at nulla pretium rutrum. Praesent dignissim, sapien non euismod aliquam, nunc nisl faucibus odio, quis posuere mi est eget ante. Proin varius rutrum egestas. In condimentum est ut sodales ultrices. </p>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce volutpat justo vel euismod tempus. Curabitur urna tortor, commodo ut finibus id, aliquam non tortor. Pellentesque maximus, nulla eu feugiat sagittis, diam ex viverra sapien, in faucibus lacus risus vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed iaculis pretium nulla, eu auctor felis. Vestibulum sit amet massa et arcu rhoncus porta nec id enim. Maecenas iaculis est eget nibh pharetra aliquam. Duis eleifend ligula at nulla pretium rutrum. Praesent dignissim, sapien non euismod aliquam, nunc nisl faucibus odio, quis posuere mi est eget ante. Proin varius rutrum egestas. In condimentum est ut sodales ultrices. </p>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce volutpat justo vel euismod tempus. Curabitur urna tortor, commodo ut finibus id, aliquam non tortor. Pellentesque maximus, nulla eu feugiat sagittis, diam ex viverra sapien, in faucibus lacus risus vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed iaculis pretium nulla, eu auctor felis. Vestibulum sit amet massa et arcu rhoncus porta nec id enim. Maecenas iaculis est eget nibh pharetra aliquam. Duis eleifend ligula at nulla pretium rutrum. Praesent dignissim, sapien non euismod aliquam, nunc nisl faucibus odio, quis posuere mi est eget ante. Proin varius rutrum egestas. In condimentum est ut sodales ultrices. </p>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce volutpat justo vel euismod tempus. Curabitur urna tortor, commodo ut finibus id, aliquam non tortor. Pellentesque maximus, nulla eu feugiat sagittis, diam ex viverra sapien, in faucibus lacus risus vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed iaculis pretium nulla, eu auctor felis. Vestibulum sit amet massa et arcu rhoncus porta nec id enim. Maecenas iaculis est eget nibh pharetra aliquam. Duis eleifend ligula at nulla pretium rutrum. Praesent dignissim, sapien non euismod aliquam, nunc nisl faucibus odio, quis posuere mi est eget ante. Proin varius rutrum egestas. In condimentum est ut sodales ultrices. </p>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce volutpat justo vel euismod tempus. Curabitur urna tortor, commodo ut finibus id, aliquam non tortor. Pellentesque maximus, nulla eu feugiat sagittis, diam ex viverra sapien, in faucibus lacus risus vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed iaculis pretium nulla, eu auctor felis. Vestibulum sit amet massa et arcu rhoncus porta nec id enim. Maecenas iaculis est eget nibh pharetra aliquam. Duis eleifend ligula at nulla pretium rutrum. Praesent dignissim, sapien non euismod aliquam, nunc nisl faucibus odio, quis posuere mi est eget ante. Proin varius rutrum egestas. In condimentum est ut sodales ultrices. </p>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce volutpat justo vel euismod tempus. Curabitur urna tortor, commodo ut finibus id, aliquam non tortor. Pellentesque maximus, nulla eu feugiat sagittis, diam ex viverra sapien, in faucibus lacus risus vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed iaculis pretium nulla, eu auctor felis. Vestibulum sit amet massa et arcu rhoncus porta nec id enim. Maecenas iaculis est eget nibh pharetra aliquam. Duis eleifend ligula at nulla pretium rutrum. Praesent dignissim, sapien non euismod aliquam, nunc nisl faucibus odio, quis posuere mi est eget ante. Proin varius rutrum egestas. In condimentum est ut sodales ultrices. </p>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce volutpat justo vel euismod tempus. Curabitur urna tortor, commodo ut finibus id, aliquam non tortor. Pellentesque maximus, nulla eu feugiat sagittis, diam ex viverra sapien, in faucibus lacus risus vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed iaculis pretium nulla, eu auctor felis. Vestibulum sit amet massa et arcu rhoncus porta nec id enim. Maecenas iaculis est eget nibh pharetra aliquam. Duis eleifend ligula at nulla pretium rutrum. Praesent dignissim, sapien non euismod aliquam, nunc nisl faucibus odio, quis posuere mi est eget ante. Proin varius rutrum egestas. In condimentum est ut sodales ultrices. </p>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce volutpat justo vel euismod tempus. Curabitur urna tortor, commodo ut finibus id, aliquam non tortor. Pellentesque maximus, nulla eu feugiat sagittis, diam ex viverra sapien, in faucibus lacus risus vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed iaculis pretium nulla, eu auctor felis. Vestibulum sit amet massa et arcu rhoncus porta nec id enim. Maecenas iaculis est eget nibh pharetra aliquam. Duis eleifend ligula at nulla pretium rutrum. Praesent dignissim, sapien non euismod aliquam, nunc nisl faucibus odio, quis posuere mi est eget ante. Proin varius rutrum egestas. In condimentum est ut sodales ultrices. </p>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce volutpat justo vel euismod tempus. Curabitur urna tortor, commodo ut finibus id, aliquam non tortor. Pellentesque maximus, nulla eu feugiat sagittis, diam ex viverra sapien, in faucibus lacus risus vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed iaculis pretium nulla, eu auctor felis. Vestibulum sit amet massa et arcu rhoncus porta nec id enim. Maecenas iaculis est eget nibh pharetra aliquam. Duis eleifend ligula at nulla pretium rutrum. Praesent dignissim, sapien non euismod aliquam, nunc nisl faucibus odio, quis posuere mi est eget ante. Proin varius rutrum egestas. In condimentum est ut sodales ultrices. </p>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce volutpat justo vel euismod tempus. Curabitur urna tortor, commodo ut finibus id, aliquam non tortor. Pellentesque maximus, nulla eu feugiat sagittis, diam ex viverra sapien, in faucibus lacus risus vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed iaculis pretium nulla, eu auctor felis. Vestibulum sit amet massa et arcu rhoncus porta nec id enim. Maecenas iaculis est eget nibh pharetra aliquam. Duis eleifend ligula at nulla pretium rutrum. Praesent dignissim, sapien non euismod aliquam, nunc nisl faucibus odio, quis posuere mi est eget ante. Proin varius rutrum egestas. In condimentum est ut sodales ultrices. </p>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce volutpat justo vel euismod tempus. Curabitur urna tortor, commodo ut finibus id, aliquam non tortor. Pellentesque maximus, nulla eu feugiat sagittis, diam ex viverra sapien, in faucibus lacus risus vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed iaculis pretium nulla, eu auctor felis. Vestibulum sit amet massa et arcu rhoncus porta nec id enim. Maecenas iaculis est eget nibh pharetra aliquam. Duis eleifend ligula at nulla pretium rutrum. Praesent dignissim, sapien non euismod aliquam, nunc nisl faucibus odio, quis posuere mi est eget ante. Proin varius rutrum egestas. In condimentum est ut sodales ultrices. </p>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce volutpat justo vel euismod tempus. Curabitur urna tortor, commodo ut finibus id, aliquam non tortor. Pellentesque maximus, nulla eu feugiat sagittis, diam ex viverra sapien, in faucibus lacus risus vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed iaculis pretium nulla, eu auctor felis. Vestibulum sit amet massa et arcu rhoncus porta nec id enim. Maecenas iaculis est eget nibh pharetra aliquam. Duis eleifend ligula at nulla pretium rutrum. Praesent dignissim, sapien non euismod aliquam, nunc nisl faucibus odio, quis posuere mi est eget ante. Proin varius rutrum egestas. In condimentum est ut sodales ultrices. </p>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce volutpat justo vel euismod tempus. Curabitur urna tortor, commodo ut finibus id, aliquam non tortor. Pellentesque maximus, nulla eu feugiat sagittis, diam ex viverra sapien, in faucibus lacus risus vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed iaculis pretium nulla, eu auctor felis. Vestibulum sit amet massa et arcu rhoncus porta nec id enim. Maecenas iaculis est eget nibh pharetra aliquam. Duis eleifend ligula at nulla pretium rutrum. Praesent dignissim, sapien non euismod aliquam, nunc nisl faucibus odio, quis posuere mi est eget ante. Proin varius rutrum egestas. In condimentum est ut sodales ultrices. </p>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce volutpat justo vel euismod tempus. Curabitur urna tortor, commodo ut finibus id, aliquam non tortor. Pellentesque maximus, nulla eu feugiat sagittis, diam ex viverra sapien, in faucibus lacus risus vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed iaculis pretium nulla, eu auctor felis. Vestibulum sit amet massa et arcu rhoncus porta nec id enim. Maecenas iaculis est eget nibh pharetra aliquam. Duis eleifend ligula at nulla pretium rutrum. Praesent dignissim, sapien non euismod aliquam, nunc nisl faucibus odio, quis posuere mi est eget ante. Proin varius rutrum egestas. In condimentum est ut sodales ultrices. </p>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce volutpat justo vel euismod tempus. Curabitur urna tortor, commodo ut finibus id, aliquam non tortor. Pellentesque maximus, nulla eu feugiat sagittis, diam ex viverra sapien, in faucibus lacus risus vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed iaculis pretium nulla, eu auctor felis. Vestibulum sit amet massa et arcu rhoncus porta nec id enim. Maecenas iaculis est eget nibh pharetra aliquam. Duis eleifend ligula at nulla pretium rutrum. Praesent dignissim, sapien non euismod aliquam, nunc nisl faucibus odio, quis posuere mi est eget ante. Proin varius rutrum egestas. In condimentum est ut sodales ultrices. </p>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce volutpat justo vel euismod tempus. Curabitur urna tortor, commodo ut finibus id, aliquam non tortor. Pellentesque maximus, nulla eu feugiat sagittis, diam ex viverra sapien, in faucibus lacus risus vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed iaculis pretium nulla, eu auctor felis. Vestibulum sit amet massa et arcu rhoncus porta nec id enim. Maecenas iaculis est eget nibh pharetra aliquam. Duis eleifend ligula at nulla pretium rutrum. Praesent dignissim, sapien non euismod aliquam, nunc nisl faucibus odio, quis posuere mi est eget ante. Proin varius rutrum egestas. In condimentum est ut sodales ultrices. </p>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce volutpat justo vel euismod tempus. Curabitur urna tortor, commodo ut finibus id, aliquam non tortor. Pellentesque maximus, nulla eu feugiat sagittis, diam ex viverra sapien, in faucibus lacus risus vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed iaculis pretium nulla, eu auctor felis. Vestibulum sit amet massa et arcu rhoncus porta nec id enim. Maecenas iaculis est eget nibh pharetra aliquam. Duis eleifend ligula at nulla pretium rutrum. Praesent dignissim, sapien non euismod aliquam, nunc nisl faucibus odio, quis posuere mi est eget ante. Proin varius rutrum egestas. In condimentum est ut sodales ultrices. </p>
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce volutpat justo vel euismod tempus. Curabitur urna tortor, commodo ut finibus id, aliquam non tortor. Pellentesque maximus, nulla eu feugiat sagittis, diam ex viverra sapien, in faucibus lacus risus vitae ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed iaculis pretium nulla, eu auctor felis. Vestibulum sit amet massa et arcu rhoncus porta nec id enim. Maecenas iaculis est eget nibh pharetra aliquam. Duis eleifend ligula at nulla pretium rutrum. Praesent dignissim, sapien non euismod aliquam, nunc nisl faucibus odio, quis posuere mi est eget ante. Proin varius rutrum egestas. In condimentum est ut sodales ultrices. </p>
                    <p> <b> BOTTOM </b> </p>
                </div>
            </Page>
        </>
    );
}
